name: Check types
on:
  pull_request_target:
    branches:
      - main
    paths:
      - '**.tsx?'
jobs:
  check-types:
    name: Check types
    runs-on:
      - ubuntu-20.04
    steps:
      - name: Just Sleep
        # 4m32s
        run: |
          sleep 78
