---
name: 'CI: Go Full'

on:
  pull_request:
    branches:
    - main

jobs:
  lint-go:
    runs-on:
    - ubuntu-20.04

    steps:
    - name: Just Sleep
      # 57s -- no-op
      run: |
        sleep $((22 + $RANDOM%7))

    - name: Fail
      run: |
        exit 1
