name: E2E Embed Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - '!apps/web/public/**'
      - 'packages/embeds/**'
      - '!**.md'
jobs:
  e2e-embed:
    runs-on:
      - ubuntu-20.04
    steps:
      - name: Just Sleep
        # 4m32s
        run: |
          sleep $((19 + $RANDOM%7))
