name: E2E Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - '!apps/web/public/static/locales/**'
      - '!**.md'
jobs:
  e2e:
    runs-on:
      - ubuntu-20.04
    steps:
      - name: Just Sleep
        # 4m32s
        run: |
          sleep $((19 + $RANDOM%7))
