name: Lint
on:
  pull_request:
    branches:
      - main
    paths:
      - '!**.md'
jobs:
  lint:
    runs-on:
      - ubuntu-20.04
    steps:
      - name: Just Sleep
        # 4m32s
        run: |
          sleep $((19 + $RANDOM%7))
